import * as React from 'react';
import { SvgCss } from 'react-native-svg';

interface Props {
  width?: number;
  height?: number;
  color?: string;
}

const DefaultLogoIcon: React.FC<Props> = ({ width, height, color }) => {
  return (
    <SvgCss
      xml={`<?xml version="1.0" encoding="UTF-8"?>
      <svg width="115px" height="113px" viewBox="0 0 115 113" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
       <!-- Generated by Pixelmator Pro 1.5.4 -->
       <g id="logo-3-final">
        <g id="XMLID_20_">
         <g id="XMLID_21_">
          <path id="XMLID_22_" d="M70.143 1.054 C69.175 0.051 67.696 -0.266 66.403 0.254 L19.58 17.485 C18.586 17.845 17.803 18.628 17.443 19.622 L0.214 66.445 C-0.19 67.539 -0.035 68.762 0.63 69.72 1.296 70.678 2.387 71.251 3.554 71.254 3.962 71.252 4.367 71.185 4.754 71.054 L51.643 53.754 C52.637 53.394 53.42 52.611 53.78 51.617 L71.08 4.795 C71.484 3.471 71.123 2.032 70.143 1.054 Z M47.566 47.609 L9.561 61.636 23.588 23.63 61.594 9.603 Z" fill="#15113d" fill-opacity="1" stroke="none"/>
         </g>
        </g>
        <path id="XMLID_19_" d="M111.89 42.799 L76.421 7.332 71.345 12.408 105.209 46.272 89.309 89.354 46.227 105.254 12.366 71.387 7.29 76.463 42.757 111.932 C43.431 112.606 44.342 112.99 45.295 113.001 45.725 112.995 46.152 112.927 46.564 112.801 L93.386 95.501 C94.38 95.141 95.163 94.358 95.523 93.364 L112.823 46.542 C113.228 45.218 112.869 43.778 111.89 42.799 Z" fill="#15113d" fill-opacity="1" stroke="none"/>
        <g id="XMLID_16_">
         <g id="XMLID_17_">
          <path id="XMLID_18_" d="M94.635 89.627 L89.582 94.681 54.112 59.211 59.166 54.157 Z" fill="#15113d" fill-opacity="1" stroke="none"/>
         </g>
        </g>
       </g>
      </svg>`}
      width={width}
      height={height}
      fill={color}
    />
  );
};
export { DefaultLogoIcon };
